language: go

matrix:
  fast_finish: true
  include:
  - go: 1.12.x
    env: GO111MODULE=on

git:
  depth: 10

before_install:
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go";

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
  - go get github.com/go-playground/overalls #overalls能够支持到各级子目录
  - go get github.com/mattn/goveralls #goveralls是coveralls对golang的测试覆盖率支持命令
  - go get github.com/smartystreets/goconvey#很好用的测试工具

script: # 集成脚本
  - overalls -project=github.com/yangwenmai/how-to-add-badge-in-github-readme -covermode=count -ignore='.git,_vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race -coverprofile=coverage.txt -covermode=atomic # 注意要添加这一行，否则不会出现 codecov bot
  - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
go_import_path: github.com/lalolv/data-worker
